-- Database Schema Initialization for FinCore

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('CUSTOMER', 'MERCHANT', 'ADMIN', 'AUDITOR')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Ensure index on email for quick login lookup
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Wallets Table
CREATE TABLE IF NOT EXISTS wallets (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED')),
    available_balance BIGINT NOT NULL DEFAULT 0,
    pending_balance BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_wallets_user_id ON wallets(user_id);

-- Ledger Accounts Table
CREATE TABLE IF NOT EXISTS ledger_accounts (
    id SERIAL PRIMARY KEY,
    holder_type VARCHAR(50) NOT NULL CHECK (holder_type IN ('CUSTOMER', 'MERCHANT', 'SYSTEM')),
    holder_id INTEGER, -- References users.id or similar, can be null for system account pools
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ledger_accounts_holder ON ledger_accounts(holder_type, holder_id);

-- Ledger Transactions Table
CREATE TABLE IF NOT EXISTS ledger_transactions (
    id VARCHAR(100) PRIMARY KEY, -- uuid generated by app
    reference_type VARCHAR(50) NOT NULL, -- 'TRANSFER', 'PAYMENT', 'REFUND'
    reference_id VARCHAR(100), -- corresponding business ID
    status VARCHAR(50) NOT NULL DEFAULT 'POSTED',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Ledger Entries Table (Double-entry line items)
CREATE TABLE IF NOT EXISTS ledger_entries (
    id SERIAL PRIMARY KEY,
    ledger_transaction_id VARCHAR(100) NOT NULL REFERENCES ledger_transactions(id) ON DELETE CASCADE,
    ledger_account_id INTEGER NOT NULL REFERENCES ledger_accounts(id),
    direction VARCHAR(20) NOT NULL CHECK (direction IN ('DEBIT', 'CREDIT')),
    amount BIGINT NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ledger_entries_transaction ON ledger_entries(ledger_transaction_id);

-- Transfers Table
CREATE TABLE IF NOT EXISTS transfers (
    id VARCHAR(100) PRIMARY KEY, -- uuid generated by app
    sender_wallet_id INTEGER NOT NULL REFERENCES wallets(id),
    recipient_wallet_id INTEGER NOT NULL REFERENCES wallets(id),
    amount BIGINT NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    status VARCHAR(50) NOT NULL DEFAULT 'CREATED' CHECK (status IN ('CREATED', 'PROCESSING', 'COMPLETED', 'FAILED')),
    idempotency_key VARCHAR(255) UNIQUE,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_transfers_idempotency ON transfers(idempotency_key);

